music/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'music'

urlpatterns = [
	
	# url(r'get_object/$', views.get_object, name = 'get_object'), #для отладки
	
	url(r'^register/$', views.UserFormView.as_view(), name = 'register'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'details'),
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name = 'album-delete'),
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name = 'album-update'),
    url(r'album/add/$', views.AlbumCreate.as_view(), name = 'album-add'),
    url(r'^$', views.IndexView.as_view(), name = 'index'),

]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)	

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.urlpatterns import format_suffix_patterns
from companies import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^stocks/', views.StockList.as_view())
]

urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:           # включить . Отключал для format_suffix_...
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Эта строка опциональна и будет добавлять url'ы только при DEBUG = True

# urlpatterns += staticfiles_urlpatterns()

companies/models.py
from django.db import models

class Stock(models.Model):
	ticker = models.CharField(max_length=10)
	open = models.FloatField()
	close = models.FloatField()
	volume = models.IntegerField()

	def __str__(self):
		return self.ticker

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
	artist = models.CharField(max_length = 255)
	album_title = models.CharField(max_length = 500)
	genre = models.CharField(max_length = 100)
	album_logo = models.FileField()  #max_length = 1000

	def get_absolute_url(self):
		return reverse('music:details', kwargs={'pk': self.pk})

	def __str__(self):
		return self.album_title + ' - ' + self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete = models.CASCADE)
	file_type = models.CharField(max_length = 10)
	song_title = models.CharField(max_length = 250)
	is_favorite = models.BooleanField(default = False)

	def __str__(self):
		return self.song_title + ' - ' + str(self.id)

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget = forms.PasswordInput)


	class Meta:
		model = User
		fields = ['username', 'email', 'password']

companies/views.py
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .models import Stock
from .serializers import StockSerializer

# List all stocks or create a new one
# stocks/
class StockList(APIView):

	def get(self, request):
		stocks = Stock.objects.all()
		serializer = StockSerializer(stocks, many=True)
		return Response(serializer.data)

	def post(self, request):
		pass

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Album
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm


from django.conf import settings
from django.http import HttpResponse


class IndexView(generic.ListView):
	template_name = 'music/index.html'
	model = Album

	# the code bellow do the same as the line 8
	# def get_queryset(self):
		# return Album.objects.all() 

class DetailView(generic.DetailView):
	template_name = 'music/details.html'
	model = Album

class AlbumCreate(CreateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(UpdateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
	model = Album
	success_url = reverse_lazy('music:index')


class UserFormView(View):
	form_class = UserForm
	template_name = 'music/registration_form.html'

	# display blank form
	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	# process form data
	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():
			user = form.save(commit = False)

			# cleaned (normalized) data
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()

			# returns User objects if credentials are correct
			user = authenticate(username=username, password = password)

			if user is not None:

				if user.is_active:
					login(request, user)
					return redirect('music:index')

		return render(request, self.template_name, {'form': form})







# def get_object(self):
# 	static_files = settings.STATICFILES_DIRS
# 	static_root = settings.STATIC_ROOT
# 	media_root = settings.MEDIA_ROOT
# 	media_url = settings.MEDIA_URL

# 	if media_url:
# 		path = media_url
# 	else:
# 		path ='No object'
		
# 	return HttpResponse(path)
	

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}add album{% endblock %}

{% block body %}
<div class='container-fluid'>
	<div class='row'>
		<div class='col-md-10'>
			<div class='panel panel-default'>
				<div class='panel-body'>
					<form class='form-horizontal' action="" method='post' enctype='multipart/form-data'>
						{% csrf_token %}
						{% include 'music/form_template.html' %}
							<div class='col-md-offset-2 col-md-10'>
								<button type="submit" class='btn btn-success'>Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>



{% csrf_token %}


  
{% endblock %}
 

music/templates/music/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	 	
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static '\music\css\style.css' %}">
</head>
<body>
	<nav class='navbar navbar-inverse'>
		<div class = 'сontainer-fluid'>
			<!-- Header -->
			<div class="navbar-header">
				<button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#topNavBar'>
					<span class='icon-bar'></span>
					<span class='icon-bar'></span>
					<span class='icon-bar'></span>
				</button>
				<a class='navbar-brand' href='{% url "music:index" %}'>Nikita</a>
			</div>

			<!-- Items -->
			<div class='collapse navbar-collapse' id='topNavBar'>
				<ul class='nav navbar-nav'>
					<li class='active'>
						<a href='{% url "music:index" %}'>
							<span class='glyphicon glyphicon-cd' aria-hidden='true'>&nbsp;Albums</span>
						</a>
					</li>
					<li class='#'>
						<a href='#'>
							<span class='glyphicon glyphicon-music' aria-hidden='true'>&nbsp; Songs</span>
						</a>
					</li>
				</ul>
				<form class='navbar-form navbar-left' role='search' method='get' action='#'>
					<div class="form-group">
						<input type='text' class='form-control' name='q' value=''>
					</div>
					<button type='submit' class='btn btn-default'>Search</button>
				</form>
				<ul class='nav navbar-nav navbar-right'>
					<li class='#'>
						<a href='{% url "music:album-add" %}'>
							<span class='glyphicon glyphicon-plus' aria-hidden='true'>&nbsp;Add album</span>
						</a>
					</li>
					<li class='#'>
						<a href='#'>
							<span class='glyphicon glyphicon-off' aria-hidden='true'>&nbsp;Logout</span>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

{% block body %}
{% endblock %}

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	

</body>
</html>

music/templates/music/details.html
{% extends 'music/base.html' %}
{% block title %}details{% endblock %}

{% block body %}
      <div class='container'>
        <div class='row'>
        <!-- Left panel   -->
          <div class='col-md-4'>
            <div class='panel'>
              <div class='panel-body' class='panel-default'>
                <img src='{{ album.album_logo.url }}' class='img-responsive'>
                <h1>{{ album.album_artist }}</h1>
                <h3>{{ album.album_title }}</h3>
                <form action="{% url 'music:album-delete' album.id %}" method="post">
                {% csrf_token %}  
                  <button type="submit" class="btn btn-default"><span class='glyphicon glyphicon-trash' aria-hidden='true'></span></button>
                </form>
                  <button type="button" class="btn btn-default"><span class='glyphicon  glyphicon-star-empty' aria-hidden='true'></span></button>
              </div>
            </div>      
          </div>
          
          <p><button type="button" class="btn btn-primary">View details</button>
          
          <a href='#'> &nbsp;Add new song</a>
          
          <!-- right panel -->
          <div class='col-md-8'>
            <div class='panel panel-default'>
              <div class='panel-body' class='panel-default'>
                <h1> All songs </h1>
                <table class='table'>
                  <thead>
                    <tr>
                      <td>Title</td>
                      <td>Audiofile</td>
                      <td>Favorite</td>
                      <td>Actions</td>
                    </tr>
                  </thead>
                </table>
              </div>
            </div>      
          </div></p>
        </div>
      </div>
     

    {% csrf_token %}


  
{% endblock %}
 

music/templates/music/form_template.html
{% for field in form %}
	<div class='form-group'>
		<div class='col-md-offset-2 col-md-10'>
			<span class='text-danger small'> {{ field.errors }}</span>
		</div>
		<label class='control-label col-md-2'>{{ field.label_tag }}</label>
		<div class='col-md-10'>{{ field }}</div>
	</div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %} 

	<ul>
		<div class='container'>
			<div class='row'>
	{% for album in object_list %}
				<div class='col-md-4'>
					<div class='panel'>
						<div class='panel-body' class='panel-default'>
							<a href='{% url "music:details" album.pk %}'>
								<img src='{{ album.album_logo.url }}' class='img-responsive'>
							</a>
							<h1>{{ album.album_artist }}</h1>
							<h3>{{ album.album_title }}</h3>
							<form action='{% url "music:details" album.id %}' >	
								<button type="submit" class="btn btn-primary">View details</button>
							</form>	
							<form action="{% url 'music:album-delete' album.id %}" method='post'>
								{% csrf_token %}
								<input type='hidden' name='album_id' value='{{ album.id }}'>
								<button type="submit" class="btn btn-default"><span class='glyphicon glyphicon-trash' aria-hidden='true'></span></button>
							</form>
							<button type="button" class="btn btn-default"><span class='glyphicon  glyphicon-star-empty' aria-hidden='true'></span></button>
						</div>
					</div>			
				</div>
	{% endfor %}
			</div>

		</div>
	</ul>

{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{% block title %}to register new user{% endblock %}

{% block body %}
<div class='container-fluid'>
	<div class='row'>
		<div class='col-md-10'>
			<div class='panel panel-default'>
				<div class='panel-body'>
					<h3>Create a new account</h3>
					<form class='form-horizontal' action="" method='post' enctype='multipart/form-data'>
						{% csrf_token %}
						{% include 'music/form_template.html' %}
							<div class='col-md-offset-2 col-md-10'>
								<button type="submit" class='btn btn-success'>Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>



{% csrf_token %}


  
{% endblock %}